name: Fog Meme

on:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes UTC

jobs:
  send:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - run: python automateFog.py
