name: Send Random Meme

on:
  push:                  # ‚Üê test on every push
    branches:
      - main
  schedule:
    # every 5 minutes (UTC)
    - cron: '*/5 * * * *'

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run meme script
        run: python automateFog.py
